{% set name = "upkie" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/upkie-{{ version }}.tar.gz
  sha256: 1d96c9258237a8c22ead4bf031036029ecbbb9e7d75b1ec0ac54c5cdf4a5eacd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8
    - pyyaml >=6.0
    - gymnasium >=0.29.1
    - loop-rate-limiters >=1.0.0
    - numpy >=1.24.3
    - scipy >=1.10.0
    - upkie_description >=2.1.0
    - msgpack-python >=1.0.2

test:
  imports:
    - upkie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/upkie
  summary: Python module to control Upkie wheeled bipeds.
  dev_url: https://github.com/upkie/upkie
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
