{% set name = "upkie" %}
{% set version = "8.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/upkie-{{ version }}.tar.gz
  sha256: 17bd12eb836af4daae693d36c288ac2e1f414cb6eb0dbf1238e7b3bd1339f2d2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml >=6.0
    - gymnasium >=0.29.1
    - loop-rate-limiters >=1.0.0
    - numpy >=1.24.3
    - scipy >=1.10.0
    - upkie_description >=2.1.0
    - msgpack-python >=1.0.2

test:
  imports:
    - upkie
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/upkie
  summary: Python module to control Upkie wheeled bipeds.
  dev_url: https://github.com/upkie/upkie
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
