{% set name = "upkie" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/upkie-{{ version }}.tar.gz
  sha256: 16288ec1eabbe259e1f98724a7d0869f8e61de049d9941cfe828a524f3ea8641

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8
    - pyyaml >=6.0
    - gymnasium >=0.29.1
    - loop-rate-limiters >=1.0.0
    - numpy >=1.24.3
    - scipy >=1.10.0
    - upkie_description >=1.4.0
    - msgpack-python >=1.0.2

test:
  imports:
    - upkie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/upkie
  summary: Python module to control Upkie wheeled bipeds.
  dev_url: https://github.com/upkie/upkie
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
